# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.quitButton_3 = QtWidgets.QPushButton(self.tab)
        self.quitButton_3.setDefault(True)
        self.quitButton_3.setObjectName("quitButton_3")
        self.gridLayout_6.addWidget(self.quitButton_3, 8, 3, 1, 1)
        self.dateLabel_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateLabel_2.setFont(font)
        self.dateLabel_2.setText("")
        self.dateLabel_2.setObjectName("dateLabel_2")
        self.gridLayout_6.addWidget(self.dateLabel_2, 1, 0, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 5, 0, 1, 1)
        self.totalincomeLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalincomeLabel.setFont(font)
        self.totalincomeLabel.setText("")
        self.totalincomeLabel.setObjectName("totalincomeLabel")
        self.gridLayout_6.addWidget(self.totalincomeLabel, 4, 1, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 4, 0, 1, 1)
        self.balanceLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.balanceLabel.setFont(font)
        self.balanceLabel.setText("")
        self.balanceLabel.setObjectName("balanceLabel")
        self.gridLayout_6.addWidget(self.balanceLabel, 5, 1, 1, 2)
        self.testButton_3 = QtWidgets.QPushButton(self.tab)
        self.testButton_3.setDefault(True)
        self.testButton_3.setObjectName("testButton_3")
        self.gridLayout_6.addWidget(self.testButton_3, 7, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 3, 0, 1, 1)
        self.totalexpenseLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalexpenseLabel.setFont(font)
        self.totalexpenseLabel.setText("")
        self.totalexpenseLabel.setObjectName("totalexpenseLabel")
        self.gridLayout_6.addWidget(self.totalexpenseLabel, 3, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 2, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 6, 0, 1, 4)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(337, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.tabWidgetPage1)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 4, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.expensetypeBox = QtWidgets.QComboBox(self.tabWidgetPage1)
        self.expensetypeBox.setObjectName("expensetypeBox")
        self.gridLayout.addWidget(self.expensetypeBox, 5, 1, 1, 1)
        self.addtypeButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.addtypeButton.setDefault(True)
        self.addtypeButton.setObjectName("addtypeButton")
        self.gridLayout.addWidget(self.addtypeButton, 5, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(117, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.addexpenseButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.addexpenseButton.setAutoDefault(False)
        self.addexpenseButton.setDefault(True)
        self.addexpenseButton.setObjectName("addexpenseButton")
        self.gridLayout.addWidget(self.addexpenseButton, 9, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(319, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 10, 0, 1, 4)
        self.displayallButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.displayallButton.setDefault(True)
        self.displayallButton.setObjectName("displayallButton")
        self.gridLayout.addWidget(self.displayallButton, 11, 3, 1, 1)
        self.searchexpensesButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.searchexpensesButton.setDefault(True)
        self.searchexpensesButton.setObjectName("searchexpensesButton")
        self.gridLayout.addWidget(self.searchexpensesButton, 12, 3, 1, 1)
        self.testButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.testButton.setDefault(True)
        self.testButton.setObjectName("testButton")
        self.gridLayout.addWidget(self.testButton, 13, 3, 1, 1)
        self.quitButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.quitButton.setDefault(True)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout.addWidget(self.quitButton, 14, 3, 1, 1)
        self.dateLabel = QtWidgets.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateLabel.setFont(font)
        self.dateLabel.setText("")
        self.dateLabel.setObjectName("dateLabel")
        self.gridLayout.addWidget(self.dateLabel, 1, 0, 1, 4)
        self.notesEdit = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.notesEdit.setObjectName("notesEdit")
        self.gridLayout.addWidget(self.notesEdit, 8, 1, 1, 3)
        self.itemEdit = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.itemEdit.setObjectName("itemEdit")
        self.gridLayout.addWidget(self.itemEdit, 6, 1, 1, 3)
        self.priceEdit = QtWidgets.QDoubleSpinBox(self.tabWidgetPage1)
        self.priceEdit.setMaximum(1000000.0)
        self.priceEdit.setObjectName("priceEdit")
        self.gridLayout.addWidget(self.priceEdit, 7, 1, 1, 2)
        self.clearButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.clearButton.setDefault(True)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 9, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)
        self.dateLabel_3 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateLabel_3.setFont(font)
        self.dateLabel_3.setText("")
        self.dateLabel_3.setObjectName("dateLabel_3")
        self.gridLayout_2.addWidget(self.dateLabel_3, 1, 0, 1, 4)
        spacerItem5 = QtWidgets.QSpacerItem(338, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 0, 1, 4)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_2.addWidget(self.dateEdit_2, 4, 1, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 5, 0, 1, 1)
        self.incometypeBox = QtWidgets.QComboBox(self.tab_2)
        self.incometypeBox.setObjectName("incometypeBox")
        self.gridLayout_2.addWidget(self.incometypeBox, 5, 1, 1, 1)
        self.addtypeButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.addtypeButton_2.setDefault(True)
        self.addtypeButton_2.setObjectName("addtypeButton_2")
        self.gridLayout_2.addWidget(self.addtypeButton_2, 5, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 5, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 8, 0, 1, 1)
        self.addincomeButton = QtWidgets.QPushButton(self.tab_2)
        self.addincomeButton.setAutoDefault(False)
        self.addincomeButton.setDefault(True)
        self.addincomeButton.setObjectName("addincomeButton")
        self.gridLayout_2.addWidget(self.addincomeButton, 9, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(348, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 10, 0, 1, 4)
        self.displayallButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.displayallButton_2.setDefault(True)
        self.displayallButton_2.setObjectName("displayallButton_2")
        self.gridLayout_2.addWidget(self.displayallButton_2, 11, 3, 1, 1)
        self.searchincomeButton = QtWidgets.QPushButton(self.tab_2)
        self.searchincomeButton.setDefault(True)
        self.searchincomeButton.setObjectName("searchincomeButton")
        self.gridLayout_2.addWidget(self.searchincomeButton, 12, 3, 1, 1)
        self.testButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.testButton_2.setDefault(True)
        self.testButton_2.setObjectName("testButton_2")
        self.gridLayout_2.addWidget(self.testButton_2, 13, 3, 1, 1)
        self.quitButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.quitButton_2.setDefault(True)
        self.quitButton_2.setObjectName("quitButton_2")
        self.gridLayout_2.addWidget(self.quitButton_2, 14, 3, 1, 1)
        self.itemEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.itemEdit_2.setObjectName("itemEdit_2")
        self.gridLayout_2.addWidget(self.itemEdit_2, 6, 1, 1, 3)
        self.priceEdit_2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.priceEdit_2.setMaximum(1000000.0)
        self.priceEdit_2.setObjectName("priceEdit_2")
        self.gridLayout_2.addWidget(self.priceEdit_2, 7, 1, 1, 2)
        self.notesEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.notesEdit_2.setObjectName("notesEdit_2")
        self.gridLayout_2.addWidget(self.notesEdit_2, 8, 1, 1, 3)
        self.clearButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.clearButton_2.setDefault(True)
        self.clearButton_2.setObjectName("clearButton_2")
        self.gridLayout_2.addWidget(self.clearButton_2, 9, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.testButton_3)
        MainWindow.setTabOrder(self.testButton_3, self.quitButton_3)
        MainWindow.setTabOrder(self.quitButton_3, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.expensetypeBox)
        MainWindow.setTabOrder(self.expensetypeBox, self.addtypeButton)
        MainWindow.setTabOrder(self.addtypeButton, self.itemEdit)
        MainWindow.setTabOrder(self.itemEdit, self.priceEdit)
        MainWindow.setTabOrder(self.priceEdit, self.notesEdit)
        MainWindow.setTabOrder(self.notesEdit, self.addexpenseButton)
        MainWindow.setTabOrder(self.addexpenseButton, self.clearButton)
        MainWindow.setTabOrder(self.clearButton, self.displayallButton)
        MainWindow.setTabOrder(self.displayallButton, self.searchexpensesButton)
        MainWindow.setTabOrder(self.searchexpensesButton, self.testButton)
        MainWindow.setTabOrder(self.testButton, self.quitButton)
        MainWindow.setTabOrder(self.quitButton, self.dateEdit_2)
        MainWindow.setTabOrder(self.dateEdit_2, self.incometypeBox)
        MainWindow.setTabOrder(self.incometypeBox, self.addtypeButton_2)
        MainWindow.setTabOrder(self.addtypeButton_2, self.itemEdit_2)
        MainWindow.setTabOrder(self.itemEdit_2, self.priceEdit_2)
        MainWindow.setTabOrder(self.priceEdit_2, self.notesEdit_2)
        MainWindow.setTabOrder(self.notesEdit_2, self.addincomeButton)
        MainWindow.setTabOrder(self.addincomeButton, self.clearButton_2)
        MainWindow.setTabOrder(self.clearButton_2, self.displayallButton_2)
        MainWindow.setTabOrder(self.displayallButton_2, self.searchincomeButton)
        MainWindow.setTabOrder(self.searchincomeButton, self.testButton_2)
        MainWindow.setTabOrder(self.testButton_2, self.quitButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Business Tracker"))
        self.quitButton_3.setText(_translate("MainWindow", "Quit"))
        self.label_14.setText(_translate("MainWindow", "Overall Balance: "))
        self.label_18.setText(_translate("MainWindow", "Total Income: "))
        self.testButton_3.setText(_translate("MainWindow", "Test"))
        self.label_7.setText(_translate("MainWindow", "Tys Forge"))
        self.label_17.setText(_translate("MainWindow", "Total Expenses: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Summary"))
        self.label.setText(_translate("MainWindow", "Tys Forge"))
        self.label_2.setText(_translate("MainWindow", "Add Expense: "))
        self.label_3.setText(_translate("MainWindow", "Date: "))
        self.label_15.setText(_translate("MainWindow", "Type: "))
        self.addtypeButton.setText(_translate("MainWindow", "Add Type"))
        self.label_4.setText(_translate("MainWindow", "Item: "))
        self.label_5.setText(_translate("MainWindow", "Price: "))
        self.label_6.setText(_translate("MainWindow", "Notes: "))
        self.addexpenseButton.setText(_translate("MainWindow", "Add Expense"))
        self.displayallButton.setText(_translate("MainWindow", "Display All"))
        self.searchexpensesButton.setText(_translate("MainWindow", "Search Expenses"))
        self.testButton.setText(_translate("MainWindow", "Test"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Add Expense"))
        self.label_8.setText(_translate("MainWindow", "Tys Forge"))
        self.label_13.setText(_translate("MainWindow", "Add Income:"))
        self.label_9.setText(_translate("MainWindow", "Date: "))
        self.label_16.setText(_translate("MainWindow", "Type: "))
        self.addtypeButton_2.setText(_translate("MainWindow", "Add Type"))
        self.label_10.setText(_translate("MainWindow", "Item: "))
        self.label_11.setText(_translate("MainWindow", "Price: "))
        self.label_12.setText(_translate("MainWindow", "Notes: "))
        self.addincomeButton.setText(_translate("MainWindow", "Add Income"))
        self.displayallButton_2.setText(_translate("MainWindow", "Display All"))
        self.searchincomeButton.setText(_translate("MainWindow", "  Search Income  "))
        self.testButton_2.setText(_translate("MainWindow", "Test"))
        self.quitButton_2.setText(_translate("MainWindow", "Quit"))
        self.clearButton_2.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Add Income"))

