# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchexpenseswindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(273, 291)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 1, 1, 2)
        self.quit2Button = QtWidgets.QPushButton(self.centralwidget)
        self.quit2Button.setMinimumSize(QtCore.QSize(100, 0))
        self.quit2Button.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.quit2Button.setFont(font)
        self.quit2Button.setObjectName("quit2Button")
        self.gridLayout.addWidget(self.quit2Button, 5, 3, 1, 1)
        self.searchdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchdateButton.setMinimumSize(QtCore.QSize(100, 0))
        self.searchdateButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.searchdateButton.setFont(font)
        self.searchdateButton.setObjectName("searchdateButton")
        self.gridLayout.addWidget(self.searchdateButton, 4, 3, 1, 1)
        self.searchtypeButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchtypeButton.setMinimumSize(QtCore.QSize(100, 0))
        self.searchtypeButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.searchtypeButton.setFont(font)
        self.searchtypeButton.setObjectName("searchtypeButton")
        self.gridLayout.addWidget(self.searchtypeButton, 2, 3, 1, 1)
        self.typeBox = QtWidgets.QComboBox(self.centralwidget)
        self.typeBox.setObjectName("typeBox")
        self.gridLayout.addWidget(self.typeBox, 1, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Business Tracker - Search"))
        self.label.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Type: "))
        self.label_3.setText(_translate("MainWindow", "Date: "))
        self.quit2Button.setText(_translate("MainWindow", "Close"))
        self.searchdateButton.setText(_translate("MainWindow", "Search Date"))
        self.searchtypeButton.setText(_translate("MainWindow", "Search Type"))

